### ISSUE TITLE
photon:3 account or password is expired

### ISSUE THREAD

**Issue by liupeng0518** [vmware/photon-docker-image#10]
I used the latest image to build arm64's harobr, but after a few days of running it prompts:

sudo account or password is expired，reset your password and try again.

**Comment by koulq** [comment]
It's the same problem.

**Comment by beltran-rubo** [comment]
Same issue here. The problem is the root account is configured to expire the password in 90 days:  /etc/login.defs

```
PASS_MAX_DAYS    90
PASS_MIN_DAYS    1
```

**Comment by beltran-rubo** [comment]
This issue is still not fixed in the official Photon container.
