### ISSUE TITLE
New release for OpenSSL 3.0.7

### ISSUE THREAD

**Issue by mac-chaffee** [vmware/photon-docker-image#16]
### Is your feature request related to a problem? Please describe.

If you haven't heard the news: tomorrow, OpenSSL is putting out a "CRITICAL" patch for OpenSSL v3: https://mta.openssl.org/pipermail/openssl-announce/2022-October/000238.html

More context: https://xeiaso.net/blog/openssl-3.x-secvuln-incoming

I see that photon ships with openssl v3:

```
$ find . -name 'libssl*'
./photon-rootfs-4.0-78b27b6f7/usr/lib/libssl.so.3
```

Also noticed that here (on the "public images" tab on page 2): https://dso.docker.com/cve/DSA-2022-0001

### Describe the solution you'd like

When v3.0.7 is officially released tomorrow (1300-1700 UTC), it would be good to get a new build pushed out ASAP.

I'm sure you all are already on top of this, just filing an issue to help track!

### Additional context

Downstream issue: https://github.com/goharbor/harbor/issues/17724

**Comment by YustasSwamp** [comment]
Thanks for an update! We are working on that.

**Comment by Vad1mo** [comment]
Anny issure or pr for that that you can reference?
