### ISSUE TITLE
Upgrade toybox package

### ISSUE THREAD

**Issue by migmartri** [vmware/photon-docker-image#9]
Hi,

At Bitnami (now part of VMware), we are using this image as base image for some of our applications and something that we rely on is the sha256 program for consistency checks.

This image seems to bundle `toybox`, which in theory, should contain a replacement of coreutils' sha256sum, but the version that we have in the image seems to only contain `sha1sum`.

Are there any plans on upgrading the bundled version of `toybox` to a version that contains the sha256 subcommand? Out of curiosity, is toybox planned to be kept in the long term? We are currently stripping it out from the image (putting back coreutils) but we want to explore respecting the configuration of the original base image and hence rely on toybox in this case.

Thanks!
Miguel

```
toybox --version
toybox 0.7.7
```

**Comment by YustasSwamp** [comment]
Hi Miguel,

Photon 3.0? It is better to use https://github.com/vmware/photon/ issues for such requests.
But as internal developer, you should use internal bugzilla for better tracking. And please do it now))

We can add support for sha256sum, it does not even require toybox version update, just config file.

Toybox is our long term tool box for docker and other small images.

**Comment by migmartri** [comment]
Thanks for the update, 

I got here by following the git repo reference for what I think is the Official Docker repository meta-repo, in case that it needs to be updated. https://github.com/docker-library/official-images/blob/master/library/photon

> But as internal developer, you should use internal bugzilla for better tracking. And please do it now)

I'll try. Still getting familiar with all the internal tools we got. 

Thanks again,
